# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stock_code = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_code.setGeometry(QtCore.QRect(60, 50, 181, 31))
        self.stock_code.setObjectName("stock_code")
        self.stock_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.stock_output.setGeometry(QtCore.QRect(260, 50, 451, 501))
        self.stock_output.setObjectName("stock_output")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.ok.setObjectName("ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stock_code.setText(_translate("MainWindow", "000001"))
        self.ok.setText(_translate("MainWindow", "开始"))
